import Link from "next/link";
import { AlertTriangle, ExternalLink, ShieldCheck } from "lucide-react";
import { CategorySection } from "@/components/CategorySection";
import { PageHeader } from "@/components/PageHeader";
import { StatusPill } from "@/components/StatusPill";
import { SummaryCard } from "@/components/SummaryCard";

const docsLinks = [
  { label: "Builders Club home", href: "https://mcp.swiggy.com/builders" },
  { label: "Developers page", href: "https://mcp.swiggy.com/builders/developers/" },
  { label: "Enterprises page", href: "https://mcp.swiggy.com/builders/enterprises/" }
];

const complianceRules = [
  "Use only official Swiggy Builders Club / MCP APIs after access is granted.",
  "Do not scrape Swiggy.",
  "Do not hardcode undocumented endpoints.",
  "Do not imply live price, inventory, availability, delivery time, or order status while in mock mode.",
  "Require explicit household admin approval before checkout or order placement."
];

export default function SwiggyIntegrationPage() {
  return (
    <div className="grid gap-6">
      <PageHeader
        eyebrow="Integration"
        title="Swiggy Instamart"
        meta="Not connected"
        description="HomeStock AI is currently running on the mock grocery provider. Swiggy Builders Club integration is planned but not active."
      />

      <section className="grid gap-3 md:grid-cols-3">
        <SummaryCard label="Current status" value="Mock" detail="No Swiggy credentials configured" tone="peach" icon={AlertTriangle} />
        <SummaryCard label="Provider" value="Local" detail="Mock grocery catalog only" tone="lavender" />
        <SummaryCard label="Checkout" value="Off" detail="Admin approval still required" tone="sage" icon={ShieldCheck} />
      </section>

      <section className="rounded-[1.5rem] border border-cocoa/10 bg-paper p-5 shadow-editorial">
        <div className="flex flex-wrap items-center gap-2">
          <StatusPill tone="pending">Mock provider active</StatusPill>
          <StatusPill tone="neutral">Swiggy disconnected</StatusPill>
        </div>
        <h2 className="font-editorial mt-4 text-4xl font-semibold text-cocoa">No real Swiggy order can be placed from this build.</h2>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-bark">
          Cart estimates are generated by `MockGroceryProvider`. The `SwiggyInstamartProvider` remains a stub until official Builders Club access, credentials, and confirmed MCP schemas are available.
        </p>
      </section>

      <CategorySection title="Planned Builders Club integration">
        <div className="grid gap-3 md:grid-cols-2">
          <IntegrationStep title="1. Request access" detail="Apply through Swiggy Builders Club and receive official credentials and documentation." />
          <IntegrationStep title="2. Confirm MCP schemas" detail="Verify exact Instamart tool names, request schemas, response schemas, auth, and sandbox behavior." />
          <IntegrationStep title="3. Wire provider" detail="Implement `SwiggyInstamartProvider` behind the existing GroceryCommerceProvider interface." />
          <IntegrationStep title="4. Preserve approval" detail="Checkout remains blocked unless a household admin explicitly approves the final cart." />
        </div>
      </CategorySection>

      <CategorySection title="Compliance rules">
        <div className="grid gap-2">
          {complianceRules.map((rule) => (
            <div key={rule} className="rounded-lg border border-cocoa/10 bg-cream p-4 text-sm text-cocoa">
              {rule}
            </div>
          ))}
        </div>
      </CategorySection>

      <CategorySection title="Official docs">
        <div className="grid gap-3 md:grid-cols-3">
          {docsLinks.map((link) => (
            <Link key={link.href} href={link.href} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 rounded-lg border border-cocoa/10 bg-paper p-4 text-cocoa shadow-panel hover:bg-cream">
              <span className="font-semibold">{link.label}</span>
              <ExternalLink className="h-4 w-4" />
            </Link>
          ))}
        </div>
      </CategorySection>
    </div>
  );
}

function IntegrationStep({ title, detail }: { title: string; detail: string }) {
  return (
    <article className="rounded-lg border border-cocoa/10 bg-paper p-4 shadow-panel">
      <h3 className="font-editorial text-2xl font-semibold text-cocoa">{title}</h3>
      <p className="mt-2 text-sm leading-6 text-bark">{detail}</p>
    </article>
  );
}
