import Link from "next/link";
import { AlertTriangle, CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { CategorySection } from "@/components/CategorySection";
import { PageHeader } from "@/components/PageHeader";
import { StatusPill } from "@/components/StatusPill";
import { SummaryCard } from "@/components/SummaryCard";
import { getGroceryProviderConfig } from "@/lib/providers";

const docsLinks = [
  { label: "Builders Club home", href: "https://mcp.swiggy.com/builders" },
  { label: "Developers page", href: "https://mcp.swiggy.com/builders/developers/" },
  { label: "Enterprises page", href: "https://mcp.swiggy.com/builders/enterprises/" }
];

const complianceRules = [
  "Use only official Swiggy Builders Club / MCP APIs after access is granted.",
  "Do not scrape Swiggy.",
  "Do not hardcode undocumented endpoints.",
  "Do not fake price, inventory, availability, delivery time, or order status while in mock mode.",
  "Require explicit household admin approval before checkout or order placement."
];

const readinessChecklist = [
  "Apply for Swiggy Builders Club access.",
  "Confirm official Instamart MCP tools, authentication, schemas, and sandbox rules.",
  "Configure OAuth/client credentials through environment variables.",
  "Map GroceryCommerceProvider methods to confirmed official MCP operations.",
  "Test in an approved sandbox or test environment.",
  "Keep household admin approval before checkout or order placement."
];

export default function SwiggyIntegrationPage() {
  const providerConfig = getGroceryProviderConfig();

  return (
    <div className="grid gap-6">
      <PageHeader
        eyebrow="Integration"
        title="Swiggy Instamart"
        meta="Not connected"
        description="HomeStock AI is currently running on the mock grocery provider. Swiggy Builders Club integration is planned but not active."
      />

      <section className="grid gap-3 md:grid-cols-3">
        <SummaryCard label="Current provider" value="Mock" detail="Mock Grocery Provider active" tone="peach" icon={AlertTriangle} />
        <SummaryCard label="Swiggy status" value="Not connected" detail={providerConfig.swiggy.enabled ? "Config incomplete or stub-only" : "Builders Club disabled"} tone="lavender" />
        <SummaryCard label="Real checkout" value="Disabled" detail="Admin approval remains required" tone="sage" icon={ShieldCheck} />
      </section>

      <section className="rounded-[1.5rem] border border-cocoa/10 bg-paper p-5 shadow-editorial">
        <div className="flex flex-wrap items-center gap-2">
          <StatusPill tone="pending">Mock provider active</StatusPill>
          <StatusPill tone="neutral">Swiggy disconnected</StatusPill>
          <StatusPill tone="neutral">No real checkout</StatusPill>
        </div>
        <h2 className="font-editorial mt-4 text-4xl font-semibold text-cocoa">No real Swiggy order can be placed from this build.</h2>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-bark">
          Cart estimates are generated by MockGroceryProvider. SwiggyInstamartProvider remains a non-operational stub until official Builders Club access, credentials, and confirmed MCP schemas are available.
        </p>
      </section>

      <CategorySection title="Readiness status">
        <div className="grid gap-3 md:grid-cols-2">
          <ReadinessRow label="Requested provider" value={providerConfig.requestedProvider} />
          <ReadinessRow label="Active provider" value="MOCK" />
          <ReadinessRow label="Swiggy enabled flag" value={providerConfig.swiggy.enabled ? "Enabled" : "Disabled"} />
          <ReadinessRow label="Credentials" value={providerConfig.swiggy.configured ? "Configured for future stub testing" : "Not configured"} />
        </div>
      </CategorySection>

      <CategorySection title="Planned Builders Club integration">
        <div className="grid gap-3 md:grid-cols-2">
          {readinessChecklist.map((item, index) => (
            <IntegrationStep key={item} title={`${index + 1}. ${item}`} detail={readinessDetail(item)} />
          ))}
        </div>
      </CategorySection>

      <CategorySection title="Compliance rules">
        <div className="grid gap-2">
          {complianceRules.map((rule) => (
            <div key={rule} className="rounded-lg border border-cocoa/10 bg-cream p-4 text-sm text-cocoa">
              {rule}
            </div>
          ))}
        </div>
      </CategorySection>

      <CategorySection title="Official docs">
        <div className="grid gap-3 md:grid-cols-3">
          {docsLinks.map((link) => (
            <Link key={link.href} href={link.href} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 rounded-lg border border-cocoa/10 bg-paper p-4 text-cocoa shadow-panel hover:bg-cream">
              <span className="font-semibold">{link.label}</span>
              <ExternalLink className="h-4 w-4" />
            </Link>
          ))}
        </div>
      </CategorySection>
    </div>
  );
}

function ReadinessRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg border border-cocoa/10 bg-cream p-4">
      <span className="text-sm font-bold uppercase tracking-[0.16em] text-bark">{label}</span>
      <span className="text-right font-semibold text-cocoa">{value}</span>
    </div>
  );
}

function IntegrationStep({ title, detail }: { title: string; detail: string }) {
  return (
    <article className="rounded-lg border border-cocoa/10 bg-paper p-4 shadow-panel">
      <div className="flex items-start gap-3">
        <CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-forest" />
        <div>
          <h3 className="font-editorial text-2xl font-semibold text-cocoa">{title}</h3>
          <p className="mt-2 text-sm leading-6 text-bark">{detail}</p>
        </div>
      </div>
    </article>
  );
}

function readinessDetail(item: string) {
  if (item.includes("Apply")) return "Access, credentials, and support must come from the official Builders Club process.";
  if (item.includes("Confirm")) return "Do not invent tool names, request schemas, response schemas, auth behavior, or rate-limit assumptions.";
  if (item.includes("Configure")) return "Secrets belong in environment variables only and are not required for local mock mode.";
  if (item.includes("Map")) return "Future wiring stays behind GroceryCommerceProvider so memory and approvals remain provider-independent.";
  if (item.includes("Test")) return "Use only official sandbox or approved test environments after access is granted.";
  return "Checkout or order placement must remain blocked until explicit household admin approval.";
}
